import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Link } from "@tanstack/react-router";
import {
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ClipboardList,
  CreditCard,
  GraduationCap,
  HelpCircle,
  MessageCircle,
  Rocket,
  Sparkles,
  Star,
  TrendingUp,
  Users,
  X,
  Zap,
} from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";

// ─── Data ──────────────────────────────────────────────────────────────────

const INCLUDED_FEATURES = [
  {
    id: "feat-ai-mentor",
    icon: Bot,
    title: "AI Mentor",
    desc: "24/7 AI guidance with personalized answers tailored to your weak areas and exam targets.",
    color: "from-accent to-secondary",
  },
  {
    id: "feat-mock-tests",
    icon: ClipboardList,
    title: "50+ Mock Tests",
    desc: "Full-length practice papers with instant scoring, detailed feedback, and national rank comparison.",
    color: "from-primary to-accent",
  },
  {
    id: "feat-pyq-library",
    icon: BookOpen,
    title: "PYQ Library",
    desc: "10+ years of past year questions from UCEED, NID, and NIFT — with step-by-step solutions.",
    color: "from-secondary to-primary",
  },
  {
    id: "feat-dashboard",
    icon: BarChart3,
    title: "Smart Dashboard",
    desc: "Progress analytics, rank prediction, and topic-wise heatmaps to guide your preparation.",
    color: "from-accent to-primary",
  },
  {
    id: "feat-study-plans",
    icon: Calendar,
    title: "Personalized Study Plans",
    desc: "Adaptive daily schedules generated by AI, adjusted to your exam date and learning pace.",
    color: "from-primary to-secondary",
  },
  {
    id: "feat-doubt-solver",
    icon: MessageCircle,
    title: "Live Doubt Solver",
    desc: "Instant resolution for all your exam doubts — submit a question and get a clear answer.",
    color: "from-secondary to-accent",
  },
];

const TRUST_STATS = [
  {
    id: "stat-students",
    icon: Users,
    value: "50,000+",
    label: "Students",
    sub: "Active learners",
  },
  {
    id: "stat-success",
    icon: TrendingUp,
    value: "95%",
    label: "Success Rate",
    sub: "In target exams",
  },
  {
    id: "stat-questions",
    icon: Brain,
    value: "10,000+",
    label: "Questions",
    sub: "Curated & solved",
  },
  {
    id: "stat-faculty",
    icon: GraduationCap,
    value: "Expert",
    label: "Faculty",
    sub: "Industry mentors",
  },
];

const PLAN_COMPARISON = [
  {
    feature: "AI Mentor Sessions",
    free: "10 / day",
    pro: "Unlimited",
    premium: "Priority + Voice",
  },
  {
    feature: "Mock Tests",
    free: "5 tests",
    pro: "50+ tests",
    premium: "50+ + Custom",
  },
  {
    feature: "PYQ Library Access",
    free: "2 years",
    pro: "10 years",
    premium: "10 years + Video",
  },
  { feature: "Performance Dashboard", free: true, pro: true, premium: true },
  { feature: "Detailed Analytics", free: false, pro: true, premium: true },
  {
    feature: "Study Plans",
    free: "Basic",
    pro: "AI-Personalised",
    premium: "AI + Coach",
  },
  {
    feature: "Doubt Solver",
    free: "5 / day",
    pro: "Unlimited",
    premium: "Unlimited + Priority",
  },
  { feature: "Live Expert Sessions", free: false, pro: false, premium: true },
  { feature: "Downloadable Notes", free: false, pro: true, premium: true },
  { feature: "Score Prediction", free: false, pro: true, premium: true },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    icon: Rocket,
    title: "Sign Up Free",
    desc: "Create your account in under 30 seconds — just an email or Google sign-in. No payment details needed.",
    color: "from-primary to-accent",
  },
  {
    step: "02",
    icon: Sparkles,
    title: "Explore All Features",
    desc: "Unlock the full platform for 7 days. Try AI Mentor, take mock tests, browse the PYQ library — everything.",
    color: "from-accent to-secondary",
  },
  {
    step: "03",
    icon: CheckCircle2,
    title: "Upgrade When Ready",
    desc: "Love it? Upgrade to Pro or Premium and continue without losing any progress, bookmarks, or history.",
    color: "from-secondary to-primary",
  },
];

const FAQS = [
  {
    id: "faq-1",
    q: "Is a credit card required for the free trial?",
    a: "No — absolutely not. Sign up with your email or Google account and get instant access. No payment information is required to start your 7-day trial.",
  },
  {
    id: "faq-2",
    q: "What happens after 7 days?",
    a: "Your account automatically continues on the free plan. You keep access to basic features and all your saved data. Upgrade anytime to Pro or Premium to unlock the full platform.",
  },
  {
    id: "faq-3",
    q: "Can I cancel anytime?",
    a: "Yes — no commitment, no cancellation fees. Cancel or downgrade at any time directly from your dashboard. If you're on a paid plan, you keep access until the end of your billing period.",
  },
  {
    id: "faq-4",
    q: "Are all features available during the trial?",
    a: "Yes. All Pro features are fully unlocked for 7 days — AI Mentor, 50+ mock tests, PYQ library, analytics, and study plans. No locked features, no watered-down experience.",
  },
  {
    id: "faq-5",
    q: "How is DesignIQ different from other prep apps?",
    a: "DesignIQ is purpose-built for UCEED, NID, and NIFT — not a generic test prep platform. We offer an AI mentor trained on design exam patterns, 10+ years of curated PYQs, and design-specific mock tests that mirror the actual exam experience.",
  },
];

const TESTIMONIALS = [
  {
    id: "t1",
    name: "Priya Sharma",
    exam: "UCEED 2024 Qualifier",
    quote:
      "The AI Mentor alone is worth it. It explained visual reasoning patterns in ways my coaching center never did. Cleared UCEED in my first attempt.",
    rating: 5,
    avatar: "PS",
    avatarColor: "from-primary to-accent",
  },
  {
    id: "t2",
    name: "Arjun Mehta",
    exam: "NID 2024 Selected",
    quote:
      "The mock tests felt exactly like the real NID exam. The instant feedback on where I was going wrong was a game changer for my preparation.",
    rating: 5,
    avatar: "AM",
    avatarColor: "from-accent to-secondary",
  },
  {
    id: "t3",
    name: "Sneha Iyer",
    exam: "NIFT 2024 Top 50",
    quote:
      "I used DesignIQ for just 3 months before my NIFT exam. The personalized study plan kept me on track and I finished top 50 nationwide.",
    rating: 5,
    avatar: "SI",
    avatarColor: "from-secondary to-primary",
  },
];

// ─── Sub-components ─────────────────────────────────────────────────────────

function FAQItem({ faq, index }: { faq: (typeof FAQS)[0]; index: number }) {
  const [open, setOpen] = useState(false);
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.4, delay: index * 0.07 }}
      data-ocid={`free_trial.faq.${index + 1}`}
      className="border border-border rounded-2xl overflow-hidden"
    >
      <button
        type="button"
        onClick={() => setOpen(!open)}
        data-ocid={`free_trial.faq_toggle.${index + 1}`}
        className="w-full flex items-center justify-between px-6 py-5 text-left hover:bg-muted/40 transition-smooth bg-card"
        aria-expanded={open}
      >
        <span className="font-semibold text-foreground text-sm md:text-base pr-4">
          {faq.q}
        </span>
        <ChevronDown
          className={`w-5 h-5 text-muted-foreground flex-shrink-0 transition-transform duration-300 ${open ? "rotate-180" : ""}`}
        />
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="px-6 pb-5 bg-muted/20">
              <p className="text-muted-foreground text-sm leading-relaxed pt-4 border-t border-border">
                {faq.a}
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

const STAR_KEYS = ["s1", "s2", "s3", "s4", "s5"];
function StarRating({ count }: { count: number }) {
  return (
    <div className="flex gap-0.5">
      {STAR_KEYS.slice(0, count).map((k) => (
        <Star key={k} className="w-4 h-4 fill-yellow-400 text-yellow-400" />
      ))}
    </div>
  );
}

// ─── Page ────────────────────────────────────────────────────────────────────

export default function FreeTrialPage() {
  return (
    <div className="min-h-screen bg-background" data-ocid="free_trial.page">
      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section className="relative overflow-hidden pt-28 pb-24">
        <div className="absolute inset-0 hero-bg-gradient" />
        {/* Floating orbs */}
        <div className="absolute top-16 left-1/4 w-72 h-72 rounded-full bg-accent/15 blur-3xl pointer-events-none animate-float" />
        <div
          className="absolute bottom-0 right-1/4 w-80 h-80 rounded-full bg-secondary/10 blur-3xl pointer-events-none animate-float"
          style={{ animationDelay: "1.5s" }}
        />
        <div className="absolute top-1/2 left-8 w-40 h-40 rounded-full bg-primary/20 blur-2xl pointer-events-none" />

        <div className="relative max-w-4xl mx-auto px-6 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
          >
            <Badge className="bg-accent/20 text-accent border-accent/30 mb-6 px-4 py-2 text-sm font-semibold">
              <Zap className="w-3.5 h-3.5 mr-1.5 animate-glow-pulse" />
              7-Day Free Access · No Credit Card Required
            </Badge>

            <h1 className="text-5xl md:text-6xl lg:text-7xl font-display font-bold text-white mb-6 leading-tight tracking-tight">
              Start Your Free{" "}
              <span className="text-gradient-accent">7-Day Trial</span> Today
            </h1>

            <p className="text-xl md:text-2xl text-white/70 max-w-2xl mx-auto mb-10 leading-relaxed">
              Try every AI-powered feature — AI Mentor, mock tests, PYQ library
              — completely free. No payment details, no commitment.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/sign-in">
                <Button
                  size="lg"
                  data-ocid="free_trial.hero_cta_button"
                  className="gradient-primary text-white font-bold text-lg px-12 py-7 rounded-2xl shadow-glow hover:opacity-90 hover:-translate-y-1 transition-smooth"
                >
                  <Rocket className="w-5 h-5 mr-2" />
                  Start Free Trial
                </Button>
              </Link>
              <Link to="/explore-features">
                <Button
                  size="lg"
                  variant="outline"
                  data-ocid="free_trial.explore_features_button"
                  className="border-white/30 text-white hover:bg-white/10 font-semibold text-lg px-10 py-7 rounded-2xl transition-smooth bg-transparent"
                >
                  Explore Features
                </Button>
              </Link>
            </div>

            <div className="flex flex-wrap items-center justify-center gap-6 mt-8">
              {[
                "No Credit Card",
                "Cancel Anytime",
                "Full Access for 7 Days",
              ].map((item) => (
                <div
                  key={item}
                  className="flex items-center gap-2 text-white/60 text-sm"
                >
                  <Check className="w-4 h-4 text-secondary" />
                  {item}
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Trust Stats ──────────────────────────────────────────────────── */}
      <section
        className="bg-muted/30 border-y border-border py-12"
        data-ocid="free_trial.stats_section"
      >
        <div className="max-w-5xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {TRUST_STATS.map((stat, i) => (
              <motion.div
                key={stat.id}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
                data-ocid={`free_trial.stat.${i + 1}`}
                className="flex flex-col items-center text-center gap-3"
              >
                <div className="w-12 h-12 rounded-xl gradient-primary flex items-center justify-center shadow-glow">
                  <stat.icon className="w-6 h-6 text-white" />
                </div>
                <div>
                  <p className="font-display font-bold text-foreground text-xl leading-none">
                    {stat.value}
                  </p>
                  <p className="font-semibold text-foreground text-sm mt-0.5">
                    {stat.label}
                  </p>
                  <p className="text-muted-foreground text-xs mt-0.5">
                    {stat.sub}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── What's Included ──────────────────────────────────────────────── */}
      <section
        className="py-24 bg-background"
        data-ocid="free_trial.features_section"
      >
        <div className="max-w-6xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-16"
          >
            <Badge className="bg-primary/10 text-primary border-primary/20 mb-4 px-4 py-2">
              <Brain className="w-3.5 h-3.5 mr-1.5" />
              Everything Included
            </Badge>
            <h2 className="text-4xl md:text-5xl font-display font-bold text-foreground mb-4">
              What's Inside Your Free Trial
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Full access to our core platform — no watered-down version, no
              hidden gates. Everything unlocked for 7 days.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {INCLUDED_FEATURES.map((feat, i) => (
              <motion.div
                key={feat.id}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.09 }}
                data-ocid={`free_trial.feature_card.${i + 1}`}
                className="glass border border-border rounded-2xl p-7 hover:border-primary/40 hover:shadow-elevated transition-smooth group relative overflow-hidden"
              >
                {/* Subtle gradient border on hover via pseudo element */}
                <div
                  className={`absolute inset-x-0 top-0 h-0.5 bg-gradient-to-r ${feat.color} opacity-0 group-hover:opacity-100 transition-smooth`}
                />
                <div
                  className={`w-13 h-13 w-12 h-12 rounded-xl bg-gradient-to-br ${feat.color} flex items-center justify-center mb-5 group-hover:scale-110 transition-smooth shadow-glow`}
                >
                  <feat.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="font-display font-bold text-foreground text-lg mb-2">
                  {feat.title}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {feat.desc}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Free vs Pro vs Premium ───────────────────────────────────────── */}
      <section
        className="py-24 bg-muted/30"
        data-ocid="free_trial.comparison_section"
      >
        <div className="max-w-5xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-14"
          >
            <h2 className="text-4xl md:text-5xl font-display font-bold text-foreground mb-4">
              Free · Pro · Premium
            </h2>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto">
              See exactly what you get and what awaits you when you upgrade.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.1 }}
            data-ocid="free_trial.comparison_table"
            className="bg-card border border-border rounded-3xl overflow-hidden shadow-elevated"
          >
            {/* Header */}
            <div className="grid grid-cols-4 border-b border-border">
              <div className="px-5 py-5 text-sm font-semibold text-muted-foreground">
                Feature
              </div>
              <div className="px-4 py-5 text-center border-l border-border">
                <p className="text-sm font-bold text-foreground">Free Trial</p>
                <p className="text-xs text-muted-foreground mt-0.5">7 days</p>
              </div>
              <div className="px-4 py-5 text-center border-l border-border bg-primary/5">
                <p className="text-sm font-bold text-primary">Pro</p>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Most Popular
                </p>
              </div>
              <div className="px-4 py-5 text-center border-l border-border gradient-primary">
                <p className="text-sm font-bold text-white">Premium</p>
                <p className="text-xs text-white/70 mt-0.5">Best Results</p>
              </div>
            </div>

            {PLAN_COMPARISON.map((row, i) => (
              <div
                key={row.feature}
                data-ocid={`free_trial.comparison_row.${i + 1}`}
                className={`grid grid-cols-4 border-b border-border last:border-b-0 ${i % 2 === 0 ? "bg-background" : "bg-muted/10"}`}
              >
                <div className="px-5 py-4 text-sm font-medium text-foreground flex items-center">
                  {row.feature}
                </div>
                <TableCell value={row.free} />
                <TableCell value={row.pro} highlight />
                <TableCell value={row.premium} premium />
              </div>
            ))}
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: 0.2 }}
            className="flex justify-center mt-8"
          >
            <Link to="/sign-in">
              <Button
                data-ocid="free_trial.comparison_cta_button"
                className="gradient-primary text-white font-bold px-10 py-6 rounded-2xl shadow-glow hover:opacity-90 hover:-translate-y-0.5 transition-smooth"
              >
                Start Free Trial — Upgrade Anytime
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ── How It Works ─────────────────────────────────────────────────── */}
      <section
        className="py-24 bg-background"
        data-ocid="free_trial.how_it_works_section"
      >
        <div className="max-w-5xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-16"
          >
            <Badge className="bg-accent/10 text-accent border-accent/20 mb-4 px-4 py-2">
              <Sparkles className="w-3.5 h-3.5 mr-1.5" />
              Simple 3-Step Start
            </Badge>
            <h2 className="text-4xl md:text-5xl font-display font-bold text-foreground mb-4">
              How It Works
            </h2>
            <p className="text-lg text-muted-foreground max-w-xl mx-auto">
              From sign-up to exam-ready in three simple steps.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-8 relative">
            {/* Connector line */}
            <div className="hidden md:block absolute top-14 left-1/3 right-1/3 h-0.5 bg-gradient-to-r from-primary/30 via-accent/50 to-secondary/30 z-0" />

            {HOW_IT_WORKS.map((step, i) => (
              <motion.div
                key={step.step}
                initial={{ opacity: 0, y: 28 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.55, delay: i * 0.15 }}
                data-ocid={`free_trial.how_step.${i + 1}`}
                className="relative flex flex-col items-center text-center z-10"
              >
                {/* Step number badge */}
                <div
                  className={`w-28 h-28 rounded-2xl bg-gradient-to-br ${step.color} flex flex-col items-center justify-center mb-6 shadow-glow group-hover:scale-105 transition-smooth`}
                >
                  <step.icon className="w-9 h-9 text-white mb-1" />
                  <span className="text-white/70 text-xs font-mono font-bold">
                    {step.step}
                  </span>
                </div>
                <h3 className="font-display font-bold text-foreground text-xl mb-3">
                  {step.title}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed max-w-xs">
                  {step.desc}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Testimonials ─────────────────────────────────────────────────── */}
      <section
        className="py-24 bg-muted/30"
        data-ocid="free_trial.testimonials_section"
      >
        <div className="max-w-6xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-14"
          >
            <Badge className="bg-secondary/10 text-secondary border-secondary/20 mb-4 px-4 py-2">
              <Star className="w-3.5 h-3.5 mr-1.5 fill-current" />
              Student Success Stories
            </Badge>
            <h2 className="text-4xl md:text-5xl font-display font-bold text-foreground mb-4">
              What Our Students Say
            </h2>
            <p className="text-lg text-muted-foreground max-w-xl mx-auto">
              Real results from students who cracked UCEED, NID, and NIFT using
              DesignIQ.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            {TESTIMONIALS.map((t, i) => (
              <motion.div
                key={t.id}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                data-ocid={`free_trial.testimonial.${i + 1}`}
                className="glass border border-border rounded-2xl p-7 flex flex-col gap-5 hover:border-primary/30 hover:shadow-elevated transition-smooth"
              >
                <StarRating count={t.rating} />
                <p className="text-foreground text-sm leading-relaxed flex-1 italic">
                  "{t.quote}"
                </p>
                <div className="flex items-center gap-3 pt-4 border-t border-border">
                  <div
                    className={`w-10 h-10 rounded-full bg-gradient-to-br ${t.avatarColor} flex items-center justify-center text-white font-bold text-sm flex-shrink-0`}
                  >
                    {t.avatar}
                  </div>
                  <div>
                    <p className="font-semibold text-foreground text-sm">
                      {t.name}
                    </p>
                    <p className="text-muted-foreground text-xs">{t.exam}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────────────────── */}
      <section
        className="py-24 bg-background"
        data-ocid="free_trial.faq_section"
      >
        <div className="max-w-3xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-14"
          >
            <Badge className="bg-secondary/10 text-secondary border-secondary/20 mb-4 px-4 py-2">
              <HelpCircle className="w-3.5 h-3.5 mr-1.5" />
              FAQ
            </Badge>
            <h2 className="text-4xl md:text-5xl font-display font-bold text-foreground mb-4">
              Common Questions
            </h2>
            <p className="text-muted-foreground text-lg">
              Everything you need to know before starting your free trial.
            </p>
          </motion.div>

          <div className="space-y-3" data-ocid="free_trial.faq_list">
            {FAQS.map((faq, i) => (
              <FAQItem key={faq.id} faq={faq} index={i} />
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────────────────── */}
      <section
        className="relative overflow-hidden py-28"
        data-ocid="free_trial.cta_section"
      >
        <div className="absolute inset-0 hero-bg-gradient" />
        <div className="absolute top-0 right-0 w-96 h-96 rounded-full bg-accent/15 blur-3xl pointer-events-none animate-float" />
        <div
          className="absolute bottom-0 left-0 w-72 h-72 rounded-full bg-secondary/10 blur-3xl pointer-events-none animate-float"
          style={{ animationDelay: "2s" }}
        />

        <div className="relative max-w-3xl mx-auto px-6 text-center">
          <motion.div
            initial={{ opacity: 0, y: 28 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-accent/20 border border-accent/30 mb-8">
              <Sparkles className="w-4 h-4 text-accent animate-glow-pulse" />
              <span className="text-sm font-medium text-accent">
                Join 50,000+ students preparing smarter
              </span>
            </div>
            <h2 className="text-4xl md:text-5xl lg:text-6xl font-display font-bold text-white mb-5 leading-tight">
              Ready to Crack Your{" "}
              <span className="text-gradient-accent">Design Exam?</span>
            </h2>
            <p className="text-xl text-white/60 mb-10 max-w-xl mx-auto leading-relaxed">
              Start your free trial today. No credit card. No hidden fees. Just
              pure, AI-powered preparation for UCEED, NID, and NIFT.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/sign-in">
                <Button
                  size="lg"
                  data-ocid="free_trial.bottom_cta_button"
                  className="gradient-primary text-white font-bold text-xl px-14 py-7 rounded-2xl shadow-glow hover:opacity-90 hover:-translate-y-1 transition-smooth"
                >
                  <Rocket className="w-5 h-5 mr-2" />
                  Start Free Trial
                </Button>
              </Link>
              <Link to="/">
                <Button
                  size="lg"
                  variant="outline"
                  data-ocid="free_trial.view_pricing_button"
                  className="border-white/30 text-white hover:bg-white/10 font-semibold text-xl px-10 py-7 rounded-2xl transition-smooth bg-transparent"
                >
                  View Pricing
                </Button>
              </Link>
            </div>
            <p className="text-white/30 text-sm mt-6">
              7-day trial · No credit card · Cancel anytime · All data preserved
            </p>
          </motion.div>
        </div>
      </section>

      {/* ── Footer ───────────────────────────────────────────────────────── */}
      <footer
        className="bg-card border-t border-border py-10 px-6"
        data-ocid="free_trial.footer"
      >
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg gradient-primary flex items-center justify-center">
              <Brain className="w-4 h-4 text-white" />
            </div>
            <span className="font-display font-bold text-foreground">
              DesignIQ
            </span>
          </div>
          <div className="flex flex-wrap items-center gap-6 text-sm text-muted-foreground">
            <Link
              to="/explore-exams"
              className="hover:text-foreground transition-smooth"
              data-ocid="free_trial.footer_exams_link"
            >
              Explore Exams
            </Link>
            <Link
              to="/explore-features"
              className="hover:text-foreground transition-smooth"
              data-ocid="free_trial.footer_features_link"
            >
              Features
            </Link>
            <Link
              to="/sign-in"
              className="hover:text-foreground transition-smooth"
              data-ocid="free_trial.footer_signin_link"
            >
              Sign In
            </Link>
          </div>
          <p className="text-muted-foreground text-xs text-center md:text-right">
            © {new Date().getFullYear()}. Built with love using{" "}
            <a
              href={`https://caffeine.ai?utm_source=caffeine-footer&utm_medium=referral&utm_content=${encodeURIComponent(typeof window !== "undefined" ? window.location.hostname : "")}`}
              className="text-primary hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              caffeine.ai
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}

// ─── Tiny helper for table cells ─────────────────────────────────────────────

function TableCell({
  value,
  highlight = false,
  premium = false,
}: {
  value: boolean | string;
  highlight?: boolean;
  premium?: boolean;
}) {
  const borderClass = "border-l border-border";
  const bgClass = highlight ? "bg-primary/5" : premium ? "" : "";

  return (
    <div
      className={`px-4 py-4 flex items-center justify-center ${borderClass} ${bgClass}`}
    >
      {typeof value === "boolean" ? (
        value ? (
          <Check
            className={`w-5 h-5 ${premium ? "text-accent" : highlight ? "text-primary" : "text-secondary"}`}
          />
        ) : (
          <X className="w-5 h-5 text-muted-foreground/30" />
        )
      ) : (
        <span
          className={`text-xs font-semibold text-center ${premium ? "text-gradient-accent" : highlight ? "text-primary" : "text-muted-foreground"}`}
        >
          {value}
        </span>
      )}
    </div>
  );
}
